Pytorch Crush Course


# PyTorch 

PyTorch provides a wide range of methods for tensor operations, neural network construction, and training. 

# Tensor Operations

Here are some of the most commonly used PyTorch Operation methods:

## 1. Creating Tensors:

- torch.tensor(data): Creates a tensor from data.

- torch.zeros(size): Creates a tensor filled with zeros.

- torch.ones(size): Creates a tensor filled with ones.

- torch.empty(size): Creates an uninitialized tensor.

- torch.arange(start, end, step): Creates a 1D tensor with values from start to end with a step.

- torch.linspace(start, end, steps): Creates a 1D tensor with values linearly spaced between start and end.

In [17]:
import torch

In [ ]:
x = torch.empty(1) # scalar tensor 
x, x.item(), x.dtype, x.size(), x.shape, x.dim()

(tensor([0.]), 0.0, torch.float32, torch.Size([1]), torch.Size([1]), 1)

In [7]:
x = torch.empty(3) # vector tensor
x, x.dtype, x.size(), x.shape, x.dim()

(tensor([0., 0., 0.]), torch.float32, torch.Size([3]), torch.Size([3]), 1)

In [11]:
x = torch.empty(2, 3) # matrix tensor
x, x.dtype, x.size(), x.shape, x.dim(), x[0, 0]

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32,
 torch.Size([2, 3]),
 torch.Size([2, 3]),
 2,
 tensor(0.))

In [10]:
x = torch.empty(2, 3, 4) # 3D tensor
x, x.dtype, x.size(), x.shape, x.dim(), x.numel()

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 torch.float32,
 torch.Size([2, 3, 4]),
 torch.Size([2, 3, 4]),
 3,
 24)

In [13]:
x = torch.empty(2, 2, 3, 5) # 4D tensor
x, x.dtype, x.size(), x.shape, x.dim(), x.numel()


(tensor([[[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],
 
          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]]],
 
 
         [[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],
 
          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]]]]),
 torch.float32,
 torch.Size([2, 2, 3, 5]),
 torch.Size([2, 2, 3, 5]),
 4,
 60)

In [16]:
x = torch.rand(2, 3) # random tensor
x, x.size(), x.shape, x.dim(), x.numel()

(tensor([[0.9720, 0.3762, 0.6029],
         [0.7080, 0.3159, 0.8013]]),
 torch.Size([2, 3]),
 torch.Size([2, 3]),
 2,
 6)

In [18]:
x = torch.zeros(2, 3) # zero tensor
x, x.size(), x.shape, x.dim(), x.numel()

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 torch.Size([2, 3]),
 torch.Size([2, 3]),
 2,
 6)

In [19]:
x = torch.ones(2, 3) # ones tensor
x, x.size(), x.shape, x.dim(), x.numel()

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([2, 3]),
 torch.Size([2, 3]),
 2,
 6)

## 2. Tensor Manipulation:

- tensor.view(shape): Reshapes a tensor.

- tensor.reshape(shape): Reshapes a tensor.

- tensor.transpose(dim0, dim1): Transposes dimensions of a tensor.

- tensor.permute(dims): Permutes the dimensions of a tensor.

- tensor.unsqueeze(dim): Adds a dimension to a tensor.

- tensor.squeeze(dim): Removes a dimension from a tensor.

In [20]:
z = x.view(2, 3) # reshape tensor
z,

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),)

## 3. Mathematical Operations:

- torch.add(tensor1, tensor2): Element-wise addition.

- torch.sub(tensor1, tensor2): Element-wise subtraction.

- torch.mul(tensor1, tensor2): Element-wise multiplication.

- torch.div(tensor1, tensor2): Element-wise division.

- torch.matmul(tensor1, tensor2): Matrix multiplication.

- torch.sum(tensor, dim): Sums elements of a tensor along a dimension.

- torch.mean(tensor, dim): Computes the mean of elements along a dimension.

- torch.max(tensor, dim): Returns the maximum value along a dimension.

- torch.min(tensor, dim): Returns the minimum value along a dimension.

# Neural Network Construction

## 1. Defining Layers:

- torch.nn.Linear(in_features, out_features): Fully connected layer.

- torch.nn.Conv2d(in_channels, out_channels, kernel_size): 2D convolutional layer.

- torch.nn.MaxPool2d(kernel_size): 2D max pooling layer.

- torch.nn.ReLU(): ReLU activation function.

- torch.nn.Sigmoid(): Sigmoid activation function.

- torch.nn.Tanh(): Tanh activation function.

- torch.nn.Dropout(p): Dropout layer.

## 2. Loss Functions:

- torch.nn.CrossEntropyLoss(): Cross-entropy loss for classification.

- torch.nn.MSELoss(): Mean squared error loss for regression.

- torch.nn.BCELoss(): Binary cross-entropy loss.

## 3. Optimizers:

- torch.optim.SGD(params, lr): Stochastic gradient descent optimizer.

- torch.optim.Adam(params, lr): Adam optimizer.

- torch.optim.RMSprop(params, lr): RMSprop optimizer.

## Training and Evaluation

## 1. Training Loop:

- optimizer.zero_grad(): Clears old gradients.

- loss.backward(): Computes the gradient of the loss.

- optimizer.step(): Updates the model parameters.

## 2. Evaluation:

- model.eval(): Sets the model to evaluation mode.

- model.train(): Sets the model to training mode.

- torch.no_grad(): Context manager to disable gradient calculation.