Pytorch Crush Course

In [17]:
import torch

In [ ]:
x = torch.empty(1) # scalar tensor 
x, x.item(), x.dtype, x.size(), x.shape, x.dim()

(tensor([0.]), 0.0, torch.float32, torch.Size([1]), torch.Size([1]), 1)

In [7]:
x = torch.empty(3) # vector tensor
x, x.dtype, x.size(), x.shape, x.dim()

(tensor([0., 0., 0.]), torch.float32, torch.Size([3]), torch.Size([3]), 1)

In [11]:
x = torch.empty(2, 3) # matrix tensor
x, x.dtype, x.size(), x.shape, x.dim(), x[0, 0]

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32,
 torch.Size([2, 3]),
 torch.Size([2, 3]),
 2,
 tensor(0.))

In [10]:
x = torch.empty(2, 3, 4) # 3D tensor
x, x.dtype, x.size(), x.shape, x.dim(), x.numel()

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 torch.float32,
 torch.Size([2, 3, 4]),
 torch.Size([2, 3, 4]),
 3,
 24)

In [13]:
x = torch.empty(2, 2, 3, 5) # 4D tensor
x, x.dtype, x.size(), x.shape, x.dim(), x.numel()


(tensor([[[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],
 
          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]]],
 
 
         [[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],
 
          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]]]]),
 torch.float32,
 torch.Size([2, 2, 3, 5]),
 torch.Size([2, 2, 3, 5]),
 4,
 60)

In [16]:
x = torch.rand(2, 3) # random tensor
x, x.size(), x.shape, x.dim(), x.numel()

(tensor([[0.9720, 0.3762, 0.6029],
         [0.7080, 0.3159, 0.8013]]),
 torch.Size([2, 3]),
 torch.Size([2, 3]),
 2,
 6)